//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies.Models
{
    using System;
    
    public partial class MovieByGenre
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Rating { get; set; }
        public string Name { get; set; }
    }
}
